version: '3.3'

services:

  main:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.port=9000
        - com.df.serviceDomain=${PORTAINER_DOMAIN}
    command: -H unix:///var/run/docker.sock

networks:

  proxy:
    external: true

volumes:

  portainer:
    driver: cloudstor:aws
    external: false